site_name: CHASO - Kreatives Chaos Solothurn
site_url: https://chaso.ch
site_description: Hackerspace und Chaostreff in Solothurn

theme:
  font: false
  logo: images/logo.png
  favicon: favicon.ico
  name: material
  language: de
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Abdunkeln

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Aufhellen
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - macros
  - blog:
      blog_dir: news
      authors: false
      blog_toc: true
  - rss:
      match_path: news/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - tags:
      tags_file: news/tags.md

repo_url: https://github.com/chaso-ch/website
edit_uri: blob/main/docs/

extra:
  social:
    - icon: fontawesome/solid/square-rss
      link: /feed_rss_updated.xml

    - icon: fontawesome/brands/github
      link: https://github.com/chaso-ch

    - icon: fontawesome/solid/paper-plane
      link: mailto:resmo_removeme_@chaso.ch

  contact:
    name: René Moser
    tel: "+41 76 332 13 67"
    email: resmo_removeme_@chaso.ch

copyright: |
  Sofern nicht anders vermerkt, stehen Inhalte unter <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de">Creatice Commons Lizenz (CC BY-NC-SA 4.0)</a>

nav:
  - Willkommen:
      - "index.md"
      - Standort: "standort.md"
      - Kontakt: "kontakt.md"
  - News:
      - "news/index.md"
      - Tags: "news/tags.md"
  - Über uns:
      - "ueber-uns/index.md"
      - Statuten: "ueber-uns/statuten.md"
