site_name: CHASO - Kreatives Chaos Solothurn

theme:
  font: false
  logo: images/logo.png
  name: material
  language: de
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Abdunkeln

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Aufhellen
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search

repo_url: https://github.com/chaso-ch/website
edit_uri: blob/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaso-ch

    - icon: fontawesome/solid/paper-plane
      link: mailto:resmo@chaso.ch

copyright: Alle Inhalte stehen unter <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de">Creatice Commons Lizenz (CC BY-NC-SA 4.0)</a>

nav:
  - Willkommen:
      - "index.md"
      - Standort: "standort.md"
      - Kontakt: "kontakt.md"
  - Über uns:
      - "ueber-uns/index.md"
      - Statuten: "ueber-uns/statuten.md"
