site_name: CHASO - Kreatives Chaos Solothurn
site_url: https://chaso.ch
site_description: Hackerspace und Chaostreff in Solothurn

theme:
  font: false
  logo: images/logo.png
  name: material
  language: de
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Abdunkeln

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Aufhellen
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - blogging:
      dirs:
        - news/posts
      size: 5
      features:
        tags: {}
      locale: de
      time_format: "%d.%m.%Y %H:%M" # The format used to display the time
      meta_time_format: "%d.%m.%Y %H:%M" # The format used to parse the time from meta

repo_url: https://github.com/chaso-ch/website
edit_uri: blob/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaso-ch

    - icon: fontawesome/solid/paper-plane
      link: mailto:resmo@chaso.ch

copyright: Sofern nicht anders vermerkt, stehen Inhalte unter <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de">Creatice Commons Lizenz (CC BY-NC-SA 4.0)</a>

nav:
  - Willkommen:
      - "index.md"
      - Standort: "standort.md"
      - Kontakt: "kontakt.md"
  - News:
      - "news/index.md"
      - Tags: "news/tags.md"
  - Über uns:
      - "ueber-uns/index.md"
      - Statuten: "ueber-uns/statuten.md"
